### PR TITLE
Add github action for auto update contributors in README.md

### PR DESCRIPTION
**Pull request by igorkamyshev**

### CODE REVIEW

**Comment by sergeysova** [comment]
What about to run action on PR merge?

**Comment by sergeysova** [comment]
Or on master branch is updated

**Comment by sergeysova** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges

**Comment by igorkamyshev** [comment]
@sergeysova good point. Done.

**Pull request merged**
