### PR TITLE
prevent infinite recursion in `UnionToStoresUnion` type

### PR DESCRIPTION
**Pull request by uulaal**
Fix for #463 

Current type has leak for infinite recursion because of `T extends any` condition - it's always true. But TS still handles this type without any issues, that's why I didn't notice the leak.

New condition has safe guard from infinite recursion and it works the same.

### CODE REVIEW

**Comment by uulaal** [comment]
Btw, there's still case to handle: optional parameters of union types:

image

If parameter is required or it's type in store is single, everything's ok: 

image
image

**Comment by uulaal** [comment]
The workaround is to exclude `undefined` here: 
image

It'll be the right solution because, if I'm not mistaken, stores can't have `undefined` state.

**Comment by zerobias** [comment]
Would you add support 

> The workaround is to exclude `undefined` here:
> image
> 
> It'll be the right solution because, if I'm not mistaken, stores can't have `undefined` state.

Would you like to commit that as well, please?

**Comment by uulaal** [comment]
Yep

**Comment by zerobias** [comment]
Looks like last change leads to regression, type test is failed https://github.com/effector/effector/pull/464/checks?check_run_id=2096398301#step:5:262
So you have to avoid that in some way. To check type tests by yourself run `yarn test --testPathPattern='types'`

**Comment by uulaal** [comment]
Can't explain why tests failed due to a simple `undefined` exclusion, but here's a ~~ugly~~ working solution

**Comment by zerobias** [comment]
Yeah, type definitions goes wild sometimes, that's why we have type tests

Thanks! 👍

**Pull request merged**
