### PR TITLE
Fix example of Gate usage in documentation

### PR DESCRIPTION
**Pull request by 7iomka**
Fix demo: wrong initial state (null, expected object) in $todo

### Conventions
- [ ] Please check your messages [against the guidelines](https://cbea.ms/git-commit/) if not, perform [interactive rebase](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history)
- [ ] [Link an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) your pull request closes or relates

### CODE REVIEW

**Review by igorkamyshev — APPROVED** [review]
I've followed the new link and found that it is broken. Could you fix it please?

Screenshot 2022-04-25 at 18 38 58

**Review by igorkamyshev — CHANGES_REQUESTED** [review]
Miss-click, sorry

**Comment by sergeysova** [comment]
@7iomka You need just uncheck `React SSR` in settings and save again

**Comment by sergeysova** [comment]
@7iomka thank you

**Pull request merged**
