### PR TITLE
fix: options api export from effector vue

### PR DESCRIPTION
**Pull request by egoson**
In this PR, the order of links in the Vue documentation has been changed, the documentation for the options api for vue 3 has been updated, links with low priority have been moved down, work has begun on exporting the options api for vue 3, this work needs to be completed and i need help)

### Conventions
- [x] Please check your messages [against the guidelines](https://cbea.ms/git-commit/) if not, perform [interactive rebase](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history)
- [x] [Link an issue](https://github.com/effector/effector/issues/1178) your pull request closes or relates
- [ ] Finish exporting option with types

### CODE REVIEW

**Comment by egoson** [comment]
I discovered that subscribing to events using watch api vue does not work, I am looking into this issue.

p.s it works normally in vue2

```ts
<template>
<button @click="someEvent">event click</button>
</template>
{
  effector: () => ({ someEvent }),
  watch: {
    someEvent() {
      console.log('does not working ')
    }
  },
  methods: { someEvent }
}
```

**Comment by egoson** [comment]
my mistake, everything works as expected, I used the effector api incorrectly 👍

**Comment by egoson** [comment]
> I discovered that subscribing to events using watch api vue does not work, I am looking into this issue.
> 
> p.s it works normally in vue2
> 
> ```ts
> // vue3 component with options api
> <template>
>   <button @click="someEvent">event click</button>
> </template>
> 
> {
>   effector: () => ({ someEvent }),
>   watch: {
>     someEvent() {
>       console.log('does not working ')
>     }
>   },
>   methods: { someEvent }
> }
> ```

my mistake, everything works as expected, I used the effector api incorrectly 👍

**Review by zerobias — APPROVED** [review]
Great, thanks!

**Pull request merged**
