### PR TITLE
Add Aviasales to list of effector users

### PR DESCRIPTION
**Pull request by igorkamyshev**
Hello! Now Aviasales uses Effector for our core product. Could you add our logo to "Companies using effector" section?

Btw, thanks for great tool 💙

### CODE REVIEW

**Comment by zarabotaet** [comment]
> Hello! Now Aviasales uses Effector for our core product. Could you add our logo to the "Companies using effector" section?
> 
> Btw, thanks for a great tool 💙

Your can also leave a comment on this issue
https://github.com/effector/effector/issues/278

**Comment by igorkamyshev** [comment]
> > Hello! Now Aviasales uses Effector for our core product. Could you add our logo to the "Companies using effector" section?
> > Btw, thanks for a great tool 💙
> 
> Your can also leave a comment in this issue
> #278

Done

**Comment by YanLobat** [comment]
Hi! Great news to hear, unfortunately, deployments are broken, for now, so I'll have to run it locally to double-check logo suits fine a bit later

**Comment by igorkamyshev** [comment]
> Hi! Great news to hear, unfortunately, deployments are broken, for now, so I'll have to run it locally to double-check logo suits fine a bit later

Something like this

Mobile
Screenshot 2021-05-21 at 12 12 56

Desktop
Screenshot 2021-05-21 at 12 12 16

**Pull request merged**
