### PR TITLE
#148 Node.js AsyncLocalStorage example

### PR DESCRIPTION
**Pull request by darky**
Example how we use Effector with Node.js + AsyncLocalStorage

### CODE REVIEW

**Comment by sergeysova** [comment]
@darky Thank you for this example!

But, why you need DI there?

**Comment by darky** [comment]
Yep, I use in example our tiny wrappers around *AsyncLocalStorage* - `ts-fp-di`, `ts-fp-di-effector`

This utils help you to bootstrap development process in proper way with Effector on Node.js with less hassle and much more clean code.

Little overhead here, that `diEff` factory required for define our **Units**
But then you can use **Stores**, **Events** or **Effects** "as is" in transparent way and it will be "magically" consider your current application lifecycle (current HTTP request, handle specific MQ message and whatever). It's like "mini-app", like Scope with specific **Events**, **Effects** or **Stores** that live in sandbox and isolated from each other.

**Comment by igorkamyshev** [comment]
In my opinion, this example will be look better in documentation for DI-library. So, maybe we should put the link to this library to awesome list.

**Comment by zerobias** [comment]
I looked after ts-fp-di for some time, interesting idea in general but I concern that it directly interferes with main effector’s concept — static (mean one-time) initialization of all units in application. This is what makes effector the effector

**Comment by sergeysova** [comment]
I think in this example DI can be replace with the Fork API

**Comment by sergeysova** [comment]
Something like this https://gist.github.com/sergeysova/289a6948a468447c21c9a1815a9e667c/revisions

But the most important thing is in the **revisions tab**

**Comment by darky** [comment]
> In my opinion, this example will be look better in documentation for DI-library. So, maybe we should put the link to this library to awesome list.

Agree, link in awesome list LGTM

> I looked after ts-fp-di development for some time, interesting idea in general but I concern that it directly interferes with main effector’s concept — static (mean one-time) initialization of all units in application. This is what makes effector the effector

Yep, it another concept. Here units allocated dynamically for each lifecycle on backend (HTTP request and so on). I don't try to sell this idea as main for Node.js development with Effector, but want pay attention of community as alternative way.

> I think in this example DI can be replace with the Fork API

Even we start develop with Fork API, but don't like it via multiple reasons:
 
1. We consider, that fork "whole world" on each HTTP request has high cost. How to scale it? We work on very large project (https://github.com/effector/effector/issues/278#issuecomment-754028333) with thousands (maybe ten thousands) units in potential. We think, that in future this will block event loop in Node.js and drastically decrease performance of our backend. From the other side, init batch of specific units for specific HTTP request look good to us.

2. Out investigation of Domain API led to the fact that it is a few fragile:

* https://effector.dev/docs/api/effector/scope#imperative-effects-calls-with-scope
* https://effector.dev/docs/api/effector/scopeBind

3. We don't want explicit work with `scope` object, pass it to any place, consider it in code. We just want to use **Stores**, **Events** or **Effects** "as is" and context will be considered automatically.

> Something like this https://gist.github.com/sergeysova/289a6948a468447c21c9a1815a9e667c/revisions

Thanks for example! I run it. Sorry, but logging don't work, seems mistake occured. Pass `domain` to `fork` method don't help.

**Comment by zerobias** [comment]
@darky performance issues have been fixed in version 22, `fork` performance has been improved by 100x. At this time, creating units per request will be tens of times slower

**Comment by zerobias** [comment]
And as for fragility - fork was implemented based on ideas from IndexedDB transactions and AsyncLocalStorage contexts, so it works with _exactly_ the same limitations

**Comment by zerobias** [comment]
@darky here is your example with Koa online:
- [https://fork-with-nodejs-kkr4026ru8so.runkit.sh/__increment__?_login_=_darky_ (published endpoint)](https://fork-with-nodejs-kkr4026ru8so.runkit.sh/increment?login=darky)
- [https://runkit.com/zerobias/fork-with-nodejs (source code)](https://runkit.com/zerobias/fork-with-nodejs)

**Comment by darky** [comment]
> performance issues have been fixed in version 22, fork performance has been improved by 100x. At this time, creating units per request will be tens of times slower

@zerobias thanks you very much for this awesome work! Really, we think about it, when Effector was 21 version. Seems event loop stuck problem can be delayed to even further. For good here need simulate stress testing with thousands units. I think about it.

> @darky here is your example with Koa online

Thanks! I run it locally and logging not working as is here https://gist.github.com/sergeysova/289a6948a468447c21c9a1815a9e667c/revisions

**Comment by sergeysova** [comment]
@darky 
> Thanks! I run it locally and logging not working as is here

You need to use babel and [effector/babel-plugin](https://effector.dev/docs/api/effector/babel-plugin/) to automatically set `sid` to each unit. That's why my example doesn't work without it.

You also can set `sid` manually as @zerobias shows

**Comment by darky** [comment]
@sergeysova set `sid` manually don't help.
@sergeysova or @zerobias can you please update your gist for working logging?

You can simply run my example and logging will be working like a charm.
I use this as :heavy_plus_sign: 1 point to `diEff` factory, it guarantee that all units will be catched and used for logging.
Logging matter on backend, you can't reproduce bug that happens 3 days ago on particular user in particular situation without logging.

**Comment by zerobias** [comment]
@darky sorry, forgot to _actually_ use the domain, example is fixed 👌 

[source code](https://runkit.com/zerobias/fork-with-nodejs/2.0.0)

real usage logs:
image

**Comment by darky** [comment]
@zerobias thanks, now logs works. But, sorry for dissatisfaction.
`pushCounterFx`, `pullCounterFx` missing in logs.
How to log effects, created by `attach` method? Or maybe stores, created by `combine` method? And so on.

**Comment by zerobias** [comment]
@darky for more complex cases I suggest to look at [patronum debug](https://github.com/effector/patronum#debug)

**Comment by darky** [comment]
> for more complex cases I suggest to look at patronum debug

Ok, it's actually that `diEff` already do - wrap unit with custom function. 

Thanks you guys for answers and time spent. No more bother with "hipster" AsyncLocalStorage Domain.

**Comment by sergeysova** [comment]
@darky Thank you for your case with DI!

**Pull request closed without merging**
